server:
  port: 8230
  servlet:
    context-path: /es
spring:
  freemarker:
    template-loader-path: classpath:/templates
    charset: UTF-8
    suffix: .ftl
    content-type: text/html
    request-context-attribute: req
  datasource:
    url: jdbc:mysql://114.55.64.105:3306/test?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: TXF19950605..
  jpa:
    show-sql: true